# Generated by Django 4.2.16 on 2024-12-12 01:48

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_tarefa_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarefa',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='tarefa',
            name='imagem',
            field=stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='tarefas', variations={'thumb': (100, 100)}),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='titulo',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
